### ISSUE TITLE
[Deadbolt and fastergt] bug or not compatible together?

### ISSUE THREAD

**Issue by korrawit** [mbknor/faster-groovy-templates#12]
I use Deadbolt and Fastergt module.

I found this problem when I use restrict tag in my view page.

I try to debug in eclipse and found this.

Catch error: ![Alt Text](http://i.imgur.com/sRKJr.jpgm)

Because after deadbolt run to line `DEADBOLT_HANDLER.beforeRoleCheck();` it will redirect,if user not logged in.

How to fix this ?

**Error**

```
@69en98853
Internal Server Error (500) for request GET /

Template execution error (In /app/views/Application/index.html around line 0)
Execution error occured in template /app/views/Application/index.html. Exception raised was GTRuntimeException : null.

play.exceptions.TemplateExecutionException
        at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:114)
        at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:73)
        at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:52)
        at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:124)
        at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
        at play.mvc.Controller.renderTemplate(Controller.java:660)
        at play.mvc.Controller.renderTemplate(Controller.java:640)
        at play.mvc.Controller.render(Controller.java:695)
        at controllers.Application.index(Application.java:23)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
        at Invocation.HTTP Request(Play!)
Caused by: play.template2.exceptions.GTRuntimeException
Caused by: play.template2.exceptions.GTRuntimeException
Caused by: play.mvc.results.Redirect
```

**Use Deadbolt in my view page**

```
#{deadbolt.restrict roles:[['Member']]}
    this restricts access to this content to role holders with the "foo" role
#{/deadbolt.restrict}
```

**Deadbolt restrict tag**

```
%{
    boolean allowAccess = false;
    for (int i = 0; !allowAccess && i < _roles.size(); i++)
    {
      allowAccess = controllers.deadbolt.Deadbolt.hasRoles(_roles.get(i))
    }
}%
#{if allowAccess}
    #{doBody /}
#{/if}
```

**hasRoles method**

```
    public static boolean hasRoles(List<String> roleNames) throws Throwable
    {
        DEADBOLT_HANDLER.beforeRoleCheck();
        RoleHolder roleHolder = getRoleHolder();

        return roleHolder != null &&
               roleHolder.getRoles() != null &&
               hasAllRoles(roleHolder,
                           roleNames.toArray(new String[roleNames.size()]));
    }

```

**Comment by mbknor** [comment]
It is a bug.

fixException() is where all the stacktrace magic happens to show correct linenumber etc.
The current version of fastergt does not handle special play-exceptions, like redirect, thrown while rendering the template.
I should fix this.

**Comment by mbknor** [comment]
After some researching I've concluded that this is not a bug, only bad error-reporting.

Performing a redirect when rendering templates is not supported in the default play implementation.

I'm working on improving the error-reporting in this case.
