### ISSUE TITLE
Closure in tag call makes compiler think it's the end of the tag

### ISSUE THREAD

**Issue by tazmaniax** [mbknor/faster-groovy-templates#13]
Hi Morten,

I have tag call where I'm trying to pass in a closure. It looks like this is confusing the compiler which thinks it's the end of the tag but not properly closed. There's no nested exception so not easy to pinpoint the source of the error. I guess the compiler needs to ignore curly braces contained within quotes. Thoughts?
# {tzselect field.name, items:models.Feedback.Type.values(), valueProperty:'name', labelProperty:'name', value:params[field.name] != null ? params[field.name]?.escape()?.raw() : field.value?.escape()?.raw(), labelMap:'{ it -> play.i18n.Messages.get("feedback.type." + it) }', class:'test', id:field.id /}

Template compilation error (In /app/views/uis/Feedback.html around line 31)
The template /app/views/uis/Feedback.html does not compile : Found unclosed tag #{tzselect}

play.exceptions.TemplateCompilationException: Found unclosed tag #{tzselect}
    at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:106)
    at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:75)
    at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:54)
    at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:128)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
    at play.mvc.Controller.renderTemplate(Controller.java:660)
    at play.mvc.Controller.renderTemplate(Controller.java:640)
    at play.mvc.Controller.render(Controller.java:695)
    at controllers.tzSecure.Secure.login(Secure.java:62)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
    at Invocation.HTTP Request(Play!)

cheers,
Chris

**Comment by tazmaniax** [comment]
Looks like tag closing has been tightened up generally because #{field} ... #{/} doesn't work anymore and now needs to be #{field} ... #{/field}

**Comment by mbknor** [comment]
it is correct that the end-tag must match the opening tag. does this solve your issue?

**Comment by tazmaniax** [comment]
I can add the #{/field} no problem but the bigger problem is my first post above where the existence of a closure '{ it -> play.i18n.Messages.get("feedback.type." + it) }' with the closing curly brace in side a tag is causing the compiler to think the tag has ended. The tag itself is closed correctly. If I remove the closure definition the template compiles correctly.

**Comment by mbknor** [comment]
Ic.

I'll have a look at the 'closing curly'-inside-tags-problem.

As a temp workaround you can probably assign the closure to a variable in a scrpt-block and then pass the variable to the tag.

**Comment by tazmaniax** [comment]
thx Morten, the work around worked. Looking at my tag now I was passing in the closure as a string literal and evaluating it but changed it so the closure can passed in directly. Can't remember why I made it a string literal.

**Comment by tazmaniax** [comment]
I think I've found a similar problem with:

${matchDetail?.getStrapline()?.replaceAll("\{", "<strong>")?.replaceAll("\}", "</strong>").raw()}

Again curly braces within quotes is interpreted as part of the tag and transferring the expression to a separate script resolves it.

**Comment by tazmaniax** [comment]
By the way, the rendering speed improvement is very noticeable and the integration as been relatively painless. Nice one.
