### ISSUE TITLE
Exception on Heroku with tag extending GTFastTag

### ISSUE THREAD

**Issue by tazmaniax** [mbknor/faster-groovy-templates#15]
Running my app with tag based on GTFastTag on my dev machine (Mac) using the standard Java runtime works fine but when I deploy to Heroku [java version "1.6.0_20", OpenJDK Runtime Environment (IcedTea6 1.9.9) (6b20-1.9.9-0ubuntu1~10.04.2), OpenJDK 64-Bit Server VM (build 19.0-b09, mixed mode)] I get the following exception. I tested with fastergt v1.3 and the latest from github (f6aacd90166d12544896a5b53215eb224d871228). I've reverted my custom Java tag to use the legacy FastTag which works fine on Heroku with the latest github fastergt.

2012-03-02T11:35:03+00:00 app[web.1]: Template execution error (In /app/views/uis/TeamStrapline.html around line 25)
2012-03-02T11:35:03+00:00 app[web.1]: Execution error occured in template /app/views/uis/TeamStrapline.html. Exception raised was RuntimeException : java.lang.reflect.InvocationTargetException.
2012-03-02T11:35:03+00:00 app[web.1]: 
2012-03-02T11:35:03+00:00 app[web.1]: play.exceptions.TemplateExecutionException: java.lang.reflect.InvocationTargetException
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:111)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:75)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:54)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:128)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.Controller.renderTemplate(Controller.java:660)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.Controller.renderTemplate(Controller.java:640)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.Controller.render(Controller.java:695)
2012-03-02T11:35:03+00:00 app[web.1]:   at controllers.Application.findTeamMembers(Application.java:249)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
2012-03-02T11:35:03+00:00 app[web.1]:   at Invocation.HTTP Request(Play!)
2012-03-02T11:35:03+00:00 app[web.1]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:128)
2012-03-02T11:35:03+00:00 app[web.1]:   at /app/views/uis/TeamStrapline.html.(line:25)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:124)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.compile.GTInternalFastTags.tag_include(GTInternalFastTags.java:118)
2012-03-02T11:35:03+00:00 app[web.1]:   at /app/views/Application/findTeamMembers.html.(line:12)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:124)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:97)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:93)
2012-03-02T11:35:03+00:00 app[web.1]:   ... 14 more
2012-03-02T11:35:03+00:00 app[web.1]: Caused by: java.lang.reflect.InvocationTargetException
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:122)
2012-03-02T11:35:03+00:00 app[web.1]:   ... 23 more
2012-03-02T11:35:03+00:00 app[web.1]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:128)
2012-03-02T11:35:03+00:00 app[web.1]:   at /app/views/uis/TeamStrapline.html.(line:22)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.legacy.GTContentRendererFakeClosure.call(GTContentRendererFakeClosure.java:67)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.templates.JavaExtensions.toString(JavaExtensions.java:76)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.InternalLegacyFastTagsImpls._form(InternalLegacyFastTagsImpls.java:96)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:122)
2012-03-02T11:35:03+00:00 app[web.1]:   ... 22 more
2012-03-02T11:35:03+00:00 app[web.1]: Caused by: java.lang.reflect.InvocationTargetException
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:122)
2012-03-02T11:35:03+00:00 app[web.1]:   ... 27 more
2012-03-02T11:35:03+00:00 app[web.1]: Caused by: java.lang.NoSuchMethodException: play.template2.generated_templates.GTTemplate__app_views_uis_TeamStrapline_html.getOut()
2012-03-02T11:35:03+00:00 app[web.1]:   at java.lang.Class.getMethod(Class.java:1622)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:212)
2012-03-02T11:35:03+00:00 app[web.1]:   at tags.HTML5ValidationTags.tag_input(HTML5ValidationTags.java:126)
2012-03-02T11:35:03+00:00 app[web.1]:   at /app/views/uis/TeamStrapline.html.(line:20)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.legacy.GTContentRendererFakeClosure.call(GTContentRendererFakeClosure.java:67)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.InternalLegacyFastTagsImpls._field(InternalLegacyFastTagsImpls.java:143)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:122)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.legacy.GTContentRendererFakeClosure.call(GTContentRendererFakeClosure.java:67)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.templates.JavaExtensions.toString(JavaExtensions.java:76)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.InternalLegacyFastTagsImpls._form(InternalLegacyFastTagsImpls.java:96)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:122)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:124)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.compile.GTInternalFastTags.tag_include(GTInternalFastTags.java:118)
2012-03-02T11:35:03+00:00 app[web.1]:   at /app/views/Application/findTeamMembers.html.(line:12)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:124)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:97)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:93)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:75)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:54)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:128)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.Controller.renderTemplate(Controller.java:660)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.Controller.renderTemplate(Controller.java:640)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.Controller.render(Controller.java:695)
2012-03-02T11:35:03+00:00 app[web.1]:   at controllers.Application.findTeamMembers(Application.java:249)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:257)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.Invoker$Invocation.run(Invoker.java:278)
2012-03-02T11:35:03+00:00 app[web.1]:   at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:235)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.util.concurrent.FutureTask.run(FutureTask.java:166)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
2012-03-02T11:35:03+00:00 app[web.1]:   at java.lang.Thread.run(Thread.java:636)

**Comment by mbknor** [comment]
Can you post the relevant source related to tags.HTML5ValidationTags.tag_input(HTML5ValidationTags.java:126) ?

**Comment by tazmaniax** [comment]
Here's what I think are the relevant snippets. Let me know if you need more.

``` html
...
#{field 'team.strapline'}
    <label for="${field.id}">&{field.name}</label>
    #{my.tags.input for:field.name, id:field.id, value:params[field.name] != null ? params[field.name]?.escape()?.raw() : field.value?.escape()?.raw(), class:field.errorClass /}
    <span class="error">${field.error}</span>
#{/field}
...
```

``` java
    public static void tag_input(GTJavaBase template, Map<String, Object> args, GTContentRenderer content) {
        try {
            // Open input tag
 line:126    template.out.append("<input");

            Map<String, String> renderArgs = new HashMap<String, String>();
            // Copy all arguments to render arguments, except for 'for' argument.
            for (final Object attribute : args.keySet()) {
                if (!"for".equalsIgnoreCase(attribute.toString()) && (args.get(attribute) != null)) {
                    renderArgs.put(attribute.toString(), args.get(attribute).toString());
                }
            }

            final String fieldName = args.get("for").toString();

            Association<Field, Object> metaData = getFieldMetaData(fieldName, template);
            ...
```

``` java
    private static Association<Field, Object> getFieldMetaData(String fieldName, GTJavaBase template) {
        final String[] pieces = fieldName.split("\\.");
        Object obj = template.binding.getVariable(pieces[0]);
        ...
```
