### ISSUE TITLE
Call to static method throws NoSuchMethodException

### ISSUE THREAD

**Issue by tazmaniax** [mbknor/faster-groovy-templates#17]
Hi Morten,

I have the following element in one of my templates:

```
<span class="right">${utils.DateUtils.format(conversation.mostRecentPostDate)}</span>
```

the called method is defined as:

```
public static String format(jave.util.Date date)
```

and the value passed in is a java.sql.Timestamp, which is a subclass of java.util.Date

Using the new fastergt I get the following exception:

Template execution error (In /app/views/Conversations/showConversations.html around line 24)
Execution error occured in template /app/views/Conversations/showConversations.html. Exception raised was NoSuchMethodException : format.

play.exceptions.TemplateExecutionException: format
    at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:111)
    at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:75)
    at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:54)
    at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:128)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
    at play.mvc.Controller.renderTemplate(Controller.java:660)
    at play.mvc.Controller.renderTemplate(Controller.java:640)
    at play.mvc.Controller.render(Controller.java:695)
    at controllers.Conversations.showConversations(Conversations.java:49)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.NoSuchMethodException: format
    at play.template2.GTJavaExtensionsInvoker.invoke(GTJavaExtensionsInvoker.java:339)
    at play.template2.GTJavaExtensionsInvoker$invoke.call(Unknown Source)
    at /app/views/Conversations/showConversations.html.(line:24)
    at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:124)
    at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
    at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:97)
    at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:93)
    ... 14 more

Looking at GTJavaExtensionsInvoker.invoke( Class jeClazz, String methodName, Object object, Object[] args) call in the debugger the params being passed in are:
jeClazz = Class play.templates.JavaExtensions
methodName = "format"
object = class utils.DateUtils
args = java.sql.Timestamp "2012-01-18 12:33:33.0"

The code looks like it's trying to find the 'format' method on the JavaExtensions class rather than the DateUtils and also looking for Timestamp class parameter and possibly not taking into account superclasses of Timestamp. 

rgds,
Chris

**Comment by mbknor** [comment]
I think u have found a bug in the JavaExtension stuff regarding statics.
I'll look into it. In the meanwhile you can rename your methodname to
something not similar to a javaextension method name. Then I think it
should work.

-morten
On Mar 15, 2012 8:04 PM, "tazmaniax" <
reply@reply.github.com>
wrote:

**Comment by tazmaniax** [comment]
thx
