### ISSUE TITLE
Error when try list a Enum

### ISSUE THREAD

**Issue by dbuarque** [mbknor/faster-groovy-templates#18]
---

HTML

---
# {list items:models.TicketType, as:'type'}

```
      <option value="${type}" >${type}</option>
```
# {/list}

---

Entity

---

public enum TicketType {

  ERROR, SUPPORT, SUGESTION

}

---

Error

---

@69pj6bm54
Internal Server Error (500) for request GET /tickets/new_admin

Template execution error (In /app/views/Tickets/new_admin.html around line 73)
Execution error occured in template /app/views/Tickets/new_admin.html. Exception raised was RuntimeException : java.lang.reflect.InvocationTargetException.

play.exceptions.TemplateExecutionException: java.lang.reflect.InvocationTargetException
    at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:111)
    at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:75)
    at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:54)
    at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:128)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
    at play.mvc.Controller.renderTemplate(Controller.java:660)
    at play.mvc.Controller.renderTemplate(Controller.java:640)
    at play.mvc.Controller.render(Controller.java:695)
    at controllers.Tickets.new_(Tickets.java:48)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:128)
    at /app/views/Tickets/new_admin.html.(line:73)
    at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:124)
    at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
    at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:97)
    at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:93)
    ... 14 more
Caused by: java.lang.reflect.InvocationTargetException
    at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:122)
    ... 19 more
Caused by: play.template2.exceptions.GTTemplateRuntimeException: Cannot convert object-reference to Iterator
    at play.template2.GTJavaBase.convertToIterator(GTJavaBase.java:341)
    at /app/views/Tickets/new_admin.html.(line:32)
    at play.template2.legacy.GTContentRendererFakeClosure.call(GTContentRendererFakeClosure.java:67)
    at play.templates.JavaExtensions.toString(JavaExtensions.java:76)
    at play.modules.gtengineplugin.InternalLegacyFastTagsImpls._form(InternalLegacyFastTagsImpls.java:96)
    at play.modules.gtengineplugin.gt_integration.GTLegacyFastTagResolver1X.legacyFastTagBridge(GTLegacyFastTagResolver1X.java:122)
    ... 18 more

**Comment by mbknor** [comment]
I'll look into it.. thanks for reporting

**Comment by mbknor** [comment]
fastergt 1.6 with this fix is now released to modules repo

**Comment by dbuarque** [comment]
Nice, great job!
