### ISSUE TITLE
Fails when using {} inside ${}

### ISSUE THREAD

**Issue by bsross** [mbknor/faster-groovy-templates#19]
template snippet:

<em class="identifier" style="background-color: #AA${Integer.toString((int)Math.floor(
                                                    65536 *
                                                    (
                                                        (
                                                            _person.country.toLowerCase().getChars().inject(0) { sum, val -> sum + Character.valueOf(val).charValue()}
                                                            - (97 \* _person.country.length())
                                                        )
                                                        / (_person.country.length() \* 26)
                                                    )
                                                ), 16)}
                    ">${_person.userId}</em>

In the log:

IInternal Server Error (500) for request POST /search/peopleandgroups?term=core

Template compilation error (In /app/views/tags/person-short.html around line 9)
The template /app/views/tags/person-short.html does not compile : unexpected tok
en: Math

play.exceptions.TemplateCompilationException: unexpected token: Math
        at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.ja
va:106)
        at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.ja
va:75)
        at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java
:54)
        at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:128)
        at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
        at play.mvc.Controller.renderTemplate(Controller.java:659)
        at play.mvc.Controller.renderTemplate(Controller.java:639)
        at play.mvc.Controller.render(Controller.java:694)
        at controllers.Search.peopleAndGroups(Search.java:35)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:546)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:500)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:476)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:471)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
        at Invocation.HTTP Request(Play!)

**Comment by mbknor** [comment]
Does this work using regular play implementation?
Does it work if you use java.lang.Math?

-morten
On Apr 27, 2012 5:00 PM, "agent613" <
reply@reply.github.com>
wrote:

**Comment by bsross** [comment]
Yes, it works with regular Play.  It only breaks with fasterGT

**Comment by bsross** [comment]
switching to java.lang.Math just changes the error to "Unexpected token: java"

**Comment by mbknor** [comment]
Thanks for clearifying.

I will have a look at it.

-morten
On Apr 27, 2012 5:23 PM, "agent613" <
reply@reply.github.com>
wrote:

**Comment by bsross** [comment]
thanks!

**Comment by mbknor** [comment]
Had some time to investigate:

The problem is not Math nut that you use ${ something {a} bb }

It uses the first } to end the expression too early - this results in invalid code..

I'll look into it..

A workaround is to resolve the value and store it in a variable in a groovy-code-block, then use the variable in the html above.

**Comment by bsross** [comment]
Ok, well I moved this logic into Java to make things simpler and avoid this. 

Unfortunately, my app still doesn't work under fastergt.  Now I get:
Template execution error (In /app/views/tags/person-details.html around line 21)

Execution error occured in template /app/views/tags/person-details.html. Exception raised was NoRouteFoundException : No route found.

play.exceptions.TemplateExecutionException: No route found
        at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:111)
        at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:75)
        at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java
:54)
        at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:128)
        at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
        at play.mvc.Controller.renderTemplate(Controller.java:659)
        at play.mvc.Controller.renderTemplate(Controller.java:639)
        at play.mvc.Controller.render(Controller.java:694)
        at controllers.Search.personDetails(Search.java:47)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:546)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:500)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:476)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:471)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
        at Invocation.HTTP Request(Play!)
Caused by: play.exceptions.NoRouteFoundException: No route found
        at play.mvc.Router.reverseWithCheck(Router.java:375)
        at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.__reverse
WithCheck(GTJavaBase1xImpl.java:35)
        at /app/views/tags/person-details.html.(line:21)
        at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:124)
        at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
        at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:97)
        at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.ja
va:93)
        ... 14 more

A snippet from around line 21 of the template:

   #{if person } *{should we check here if the user manages at least 1 group? }*
        <a id="modify-button" class="tool" href="javascript: Swarm.selectPerson('${person.userId}', false, ${!editMode})">
            <img src="@{'/public/images/' + (editMode ? 'arrow-180' : 'pencil') + '.png'}"/>
        </a>
    #{/if}

Again, this works just fine in regular Play.  

Thanks for your help,
Brian

**Comment by mbknor** [comment]
can you remove the @{...} and instead print it like this: ${'/public/images/'
- (editMode ? 'arrow-180' : 'pencil') + '.png'}

Then see what is wrong with the resolved path - this will probably give you
(and me) a hint about what is wrong.

On Thu, May 3, 2012 at 10:58 PM, agent613 <
reply@reply.github.com

**Comment by bsross** [comment]
There is nothing wrong with the resolved path.  If I switch it the way you suggested, it will work just fine on my local machine (with FasterGT and without).  However, when I try to deploy it for real, this won't work (with fasterGT or without) because the real URL doesn't begin from the root.  Using the @ will cause the resolved path to be /pubic/images on my machine, but /A/B/C/public/images on the server.

Thanks,
Brian

**Comment by mbknor** [comment]
Are u deploying as war?

So the problem is that fastergt does not prefix static url with correct
contextpath in prod?
On May 4, 2012 6:03 PM, "agent613" <
reply@reply.github.com>
wrote:

**Comment by bsross** [comment]
Yes, I deploy as a war.  I haven't even tried deploying with fastergt.
I know from past experience with standard Play that if I don't use @, then play will not prefix the URL with the correct contextpath.

**Comment by mbknor** [comment]
Please open a new ticket regarding the @ problem if you still have it.. The {} inside ${} problem is now fixed
