### ISSUE TITLE
GTEngine throws exceptin for the index template of the sample app 

### ISSUE THREAD

**Issue by zapodot** [mbknor/faster-groovy-templates#2]
The rendering of Application/index.html results in an exception wich in turn makes Play try to render the 500 error template which then results in a NPE when the TemplateException is to be logged.

Will investigate further later

Stacktrace:

```
18:43:15,613 ERROR ~ Oops. Error in Logger !
java.lang.NullPointerException
    at play.exceptions.TemplateException.getSourceFile(TemplateException.java:40)
    at play.Logger.niceThrowable(Logger.java:555)
    at play.Logger.error(Logger.java:424)
    at play.server.PlayHandler.serve500(PlayHandler.java:794)
    at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:237)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at      java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
play.template2.exceptions.GTRuntimeException
    at java.lang.Class.getGenericSuperclass(Class.java:694)
    at com.sun.beans.TypeResolver.prepare(TypeResolver.java:274)
    at com.sun.beans.TypeResolver.<init>(TypeResolver.java:243)
    at com.sun.beans.TypeResolver.resolve(TypeResolver.java:172)
    at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:93)
    at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:385)
    at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116)
    at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:74)
    at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:58)
    at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1196)
    at java.beans.Introspector.getBeanInfo(Introspector.java:423)
    at java.beans.Introspector.getBeanInfo(Introspector.java:189)
    at java.security.AccessController.doPrivileged(Native Method)
    at play.template2.legacy.GTContentRendererFakeClosure.<init>(GTContentRendererFakeClosure.java:18)
    at play.template2.GTJavaBase.invokeTagFile(GTJavaBase.java:229)
    at /app/views/Application/index.html.(line:4)
    at play.template2.GTJavaBase.internalRenderTemplate(GTJavaBase.java:122)
    at play.modules.gtengineplugin.gt_integration.GTJavaBase1xImpl.internalRenderTemplate(GTJavaBase1xImpl.java:82)
    at play.template2.GTJavaBase.renderTemplate(GTJavaBase.java:95)
    at play.modules.gtengineplugin.GTTemplate.renderGTTemplate(GTTemplate.java:91)
    at play.modules.gtengineplugin.GTTemplate.internalGTRender(GTTemplate.java:73)
    at play.modules.gtengineplugin.GTTemplate.internalRender(GTTemplate.java:52)
    at play.modules.gtengineplugin.GTTemplate.render(GTTemplate.java:123)
    at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
    at play.mvc.Controller.renderTemplate(Controller.java:660)
    at play.mvc.Controller.renderTemplate(Controller.java:640)
    at play.mvc.Controller.render(Controller.java:695)
    at controllers.Application.index(Application.java:12)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
    at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:257)
    at play.Invoker$Invocation.run(Invoker.java:278)
    at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
    ... 44 more
```

**Comment by mbknor** [comment]
It would be nice if you tries to find out why it fails here: /app/views/Application/index.html.(line:4)

Then I'll try to invoke a 500 and check why it fails with NPE.

**Comment by zapodot** [comment]
Line 4 says: #{welcome /}.

Will try to debug

**Comment by mbknor** [comment]
strange.. It works perfect when I run the test app, and when used by our big app at work.

When I provoke an error I get a nice error page.

I see this: java.beans.Introspector.getBeanInfo(Introspector.java:189) on your callstack..

Are you using some special java version?

**Comment by mbknor** [comment]
I've found the problem:

in gt-engine,  which originaly is using groovy 1.8.4, I have code like this:

```
public class GTContentRendererFakeClosure extends Closure<Object>
```

Play 1.2.4 uses Groovy 1.7.0 where Closure does not take generic param.

On my mac it works but not on windows it looks like..

I'll try to fix it as soon as possible without needing to upgrade groovy version,

**Comment by zapodot** [comment]
Running on the latest Ubuntu with:

```
java version "1.6.0_23"
OpenJDK Runtime Environment (IcedTea6 1.11pre) (6b23~pre11-0ubuntu1.11.10.1)
OpenJDK 64-Bit Server VM (build 20.0-b11, mixed mode)
```

Switching to Sun JDK:

```
java version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)
```

ét voilá, it works :-)

Will check again once you have fixed the issue in gt-engine. Would be nice to have it run on OpenJDK as well.

**Comment by mbknor** [comment]
Thanks... I'll do the "public class GTContentRendererFakeClosure extends Closure<Object>" change anyway..

**Comment by mbknor** [comment]
zapodot: Can you please change back to openjdk and try again? and also make sure it stil works for regular jvm

**Comment by zapodot** [comment]
Tested your fix using openjdk and can confirm that it resolves the issue.

**Comment by mbknor** [comment]
thanks for verifying it.
