### ISSUE TITLE
Exception with minifymod module

### ISSUE THREAD

**Issue by tazmaniax** [mbknor/faster-groovy-templates#22]
Hi,

After installing [minifymod](https://github.com/maklemenz/minifymod) module v1.0.1 with Play v1.2.4 and fastergt v1.7 I get the following exception:

```
18:23:08,594 [play-thread-1] ERROR ~ 

@6b08e68b4
Internal Server Error (500) for request GET /findteamies/search/answers

Execution exception (In {module:minifymod-1.0.1}/app/controllers/minifymod/MinifyResponse.java around line 33)
NullPointerException occured : null

play.exceptions.JavaExecutionException
    at play.mvc.ActionInvoker.handleFinallies(ActionInvoker.java:435)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:254)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException
    at controllers.minifymod.MinifyResponse.compress(MinifyResponse.java:33)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:504)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.handleFinallies(ActionInvoker.java:428)
    ... 2 more
```

The response content type is not defined and the response doesn't contain any content:

minifymod-1.0.1/controllers/minifymod/MinifyResponse.java:

```
static void compress() throws IOException {
    if(moduleEnabled && minifyEnabled && !isExcluded()) {
        // get rendered content
        String content = response.out.toString();
        // select compression method by contentType
        if (response.contentType.contains("text/html")) {   // could be "text/html; charset=utf-8"
            content = Compression.compressHTML(content);
        } else if (response.contentType.contains("text/xml")) {
            content = Compression.compressXML(content);
        } else if (response.contentType.contains("text/css")) {
            content = Compression.compressCSS(content);
        } else if (response.contentType.contains("text/javascript")) {
            content = Compression.compressJS(content);
        }
        response.out = new ByteArrayOutputStream(content.length());
        response.out.write(content.getBytes());
    }
}
```

fastergt doing something different?

I've raised a similar [issue](https://github.com/maklemenz/play-minifymod/issues/3) with minifymod.

**Comment by mbknor** [comment]
I think this one is fixed in 1.8 which include this fix: https://github.com/mbknor/gt-engine/commit/3f37b6e027acf365a147732dec907db76c56f23c

It would be nice if you could check it out - even if it has been a while since you filed the bug.
